// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	http "net/http"

	gql "github.com/weavedev/go-gqlclient"

	mock "github.com/stretchr/testify/mock"
)

// RequestBuilder is an autogenerated mock type for the RequestBuilder type
type RequestBuilder struct {
	mock.Mock
}

// Execute provides a mock function with given fields: endpoint, req
func (_m *RequestBuilder) Execute(endpoint string, req *gql.Request) (*http.Request, error) {
	ret := _m.Called(endpoint, req)

	var r0 *http.Request
	if rf, ok := ret.Get(0).(func(string, *gql.Request) *http.Request); ok {
		r0 = rf(endpoint, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*http.Request)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, *gql.Request) error); ok {
		r1 = rf(endpoint, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
